version: "3.9"

services:
  telegram-web-a:
    image: node:22-alpine
    container_name: telegram-web-a
    working_dir: /app
    environment:
      TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
      TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
      PORT: 1234
    command: >
      sh -c "
        apk add --no-cache git && \
        rm -rf /tmp/repo /app/* /app/.* || true && \
        git clone --depth 1 https://github.com/Roycce/Telegram-web-z.git /tmp/repo && \
        cp -r /tmp/repo/. /app/ && \
        echo 'Files in /app/:' && ls -la /app/ | head -20 && \
        if [ ! -f /app/package.json ]; then echo 'FATAL: package.json missing!'; exit 1; fi && \
        cd /app && \
        if [ ! -d node_modules ] || [ ! -f package-lock.json ]; then \
          npm install --verbose; \
        else \
          echo 'node_modules already installed, skipping npm install'; \
        fi && \
        npx cross-env APP_ENV=development webpack serve --mode development
      "
    volumes:
      - telegram-web-a-data:/app
      - node-modules:/app/node_modules
    networks:
      - docker_infra-net

networks:
  docker_infra-net:
    external: true

volumes:
  telegram-web-a-data:
  node-modules:
